export const heroAnimeData: Anime = {
    _id: "0",
    title: "Demon Slayer: Kimetsu no Yaiba",
    posterUrl:
        "https://m.media-amazon.com/images/I/81jH5-U+1wL._AC_UF894,1000_QL80_.jpg",
    coverUrl: "/fake/0.webp",
    logoUrl: "/fake/1.webp",
    genres: [
        {
            _id: "101",
            title: "Supernatural",
            createdAt: "2024-01-01T12:00:00Z",
            updatedAt: "2024-01-10T12:00:00Z",
        },
        {
            _id: "102",
            title: "Action",
            createdAt: "2024-01-01T12:00:00Z",
            updatedAt: "2024-01-10T12:00:00Z",
        },
        {
            _id: "103",
            title: "Award Winning",
            createdAt: "2024-01-01T12:00:00Z",
            updatedAt: "2024-01-10T12:00:00Z",
        },
    ],
    studio: {
        _id: "201",
        title: "ufotable",
        createdAt: "2024-01-01T12:00:00Z",
        updatedAt: "2024-01-10T12:00:00Z",
    },
    description:
        "Join Tanjiro on an epic quest in Demon Slayer: Kimetsu no Yaiba! Witness breathtaking battles, heartwarming bonds, and the fight against darkness in a stunning Taisho-era world. Stream now and immerse yourself in this anime phenomenon!",
    releaseDate: "2019-04-06T00:00:00Z",
    episodes: [
        {
            _id: "0",
            title: "Cruelty",
            episodeNumber: "1",
            videoUrl: "vid001",
            thumbnailUrl: "/fake/7.webp",
            duration: 1440, // 24 minutes in seconds
            createdAt: "2019-04-06T12:00:00Z",
            updatedAt: "2019-04-06T12:00:00Z",
        },
        {
            _id: "1",
            title: "Trainer Sakonji Urokodaki",
            episodeNumber: "2",
            videoUrl: "vid002",
            duration: 1440,
            createdAt: "2019-04-13T12:00:00Z",
            updatedAt: "2019-04-13T12:00:00Z",
        },
        {
            _id: "2",
            title: "Trainer Sakonji Urokodaki",
            episodeNumber: "2",
            videoUrl: "vid002",
            duration: 1440,
            createdAt: "2019-04-13T12:00:00Z",
            updatedAt: "2019-04-13T12:00:00Z",
        },
        {
            _id: "3",
            title: "Trainer Sakonji Urokodaki",
            episodeNumber: "2",
            videoUrl: "vid002",
            duration: 1440,
            createdAt: "2019-04-13T12:00:00Z",
            updatedAt: "2019-04-13T12:00:00Z",
        },
    ],
    trailerUrl: "https://example.com/demon-slayer-trailer.mp4",
    status: "completed",
    createdAt: "2019-04-01T12:00:00Z",
    updatedAt: "2024-12-06T12:00:00Z",
};
export const fakeDataList: Anime[] = [
    {
        _id: "0",
        title: "Demon Slayer: Kimetsu no Yaiba",
        posterUrl:
            "https://m.media-amazon.com/images/I/81jH5-U+1wL._AC_UF894,1000_QL80_.jpg",
        coverUrl: "/fake/0.webp",
        logoUrl: "/fake/1.webp",
        genres: [
            {
                _id: "101",
                title: "Supernatural",
                createdAt: "2024-01-01T12:00:00Z",
                updatedAt: "2024-01-10T12:00:00Z",
            },
            {
                _id: "102",
                title: "Action",
                createdAt: "2024-01-01T12:00:00Z",
                updatedAt: "2024-01-10T12:00:00Z",
            },
            {
                _id: "103",
                title: "Award Winning",
                createdAt: "2024-01-01T12:00:00Z",
                updatedAt: "2024-01-10T12:00:00Z",
            },
        ],
        studio: {
            _id: "201",
            title: "ufotable",
            createdAt: "2024-01-01T12:00:00Z",
            updatedAt: "2024-01-10T12:00:00Z",
        },
        description:
            "Join Tanjiro on an epic quest in Demon Slayer: Kimetsu no Yaiba! Witness breathtaking battles, heartwarming bonds, and the fight against darkness in a stunning Taisho-era world. Stream now and immerse yourself in this anime phenomenon!",
        releaseDate: "2019-04-06T00:00:00Z",
        episodes: [
            {
                _id: "301",
                title: "Cruelty",
                episodeNumber: "1",
                thumbnailUrl: "/fake/7.webp",
                videoUrl:
                    "https://res.cloudinary.com/duzvevuup/video/upload/v1725511724/ZZZ/Qingyi_Basic_Attack_qhizbl.mp4",
                duration: 1440, // 24 minutes in seconds
                createdAt: "2019-04-06T12:00:00Z",
                updatedAt: "2019-04-06T12:00:00Z",
            },
            {
                _id: "302",
                title: "Trainer Sakonji Urokodaki",
                episodeNumber: "2",
                videoUrl: "vid002",
                duration: 1440,
                createdAt: "2019-04-13T12:00:00Z",
                updatedAt: "2019-04-13T12:00:00Z",
            },
            {
                _id: "2",
                title: "Trainer Sakonji Urokodaki",
                episodeNumber: "2",
                videoUrl: "vid002",
                duration: 1440,
                createdAt: "2019-04-13T12:00:00Z",
                updatedAt: "2019-04-13T12:00:00Z",
            },
            {
                _id: "3",
                title: "Trainer Sakonji Urokodaki",
                episodeNumber: "2",
                videoUrl: "vid002",
                duration: 1440,
                createdAt: "2019-04-13T12:00:00Z",
                updatedAt: "2019-04-13T12:00:00Z",
            },
            {
                _id: "2",
                title: "Trainer Sakonji Urokodaki",
                episodeNumber: "2",
                videoUrl: "vid002",
                duration: 1440,
                createdAt: "2019-04-13T12:00:00Z",
                updatedAt: "2019-04-13T12:00:00Z",
            },
            {
                _id: "3",
                title: "Trainer Sakonji Urokodaki",
                episodeNumber: "2",
                videoUrl: "vid002",
                duration: 1440,
                createdAt: "2019-04-13T12:00:00Z",
                updatedAt: "2019-04-13T12:00:00Z",
            },
        ],
        trailerUrl: "https://example.com/demon-slayer-trailer.mp4",
        status: "completed",
        createdAt: "2019-04-01T12:00:00Z",
        updatedAt: "2024-12-06T12:00:00Z",
    },
    {
        _id: "1",
        title: "Dandandan",
        posterUrl: "/fake/2.webp",
        coverUrl: "https://example.com/demon-slayer-cover.jpg",
        logoUrl: "https://example.com/demon-slayer-logo.png",
        genres: [
            {
                _id: "genre_1",
                title: "Action",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
            {
                _id: "genre_2",
                title: "Adventure",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        studio: {
            _id: "studio_1",
            title: "Ufotable",
            createdAt: "2022-01-01",
            updatedAt: "2022-01-01",
        },
        description:
            "Follow Tanjiro Kamado as he fights demons in a stunning Taisho-era Japan.",
        releaseDate: "2019-04-06",
        episodes: [
            {
                _id: "episode_1",
                title: "Cruelty",
                episodeNumber: "1",
                videoUrl: "video_1",
                duration: 23,
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        trailerUrl: "https://example.com/demon-slayer-trailer.mp4",
        status: "Ongoing",
        createdAt: "2022-01-01",
        updatedAt: "2022-01-01",
    },
    {
        _id: "2",
        title: "Frieren: Beyond Journey's End",
        posterUrl: "/fake/3.webp",
        coverUrl: "https://example.com/attack-on-titan-cover.jpg",
        logoUrl: "https://example.com/attack-on-titan-logo.png",
        genres: [
            {
                _id: "genre_3",
                title: "Action",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
            {
                _id: "genre_4",
                title: "Drama",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        studio: {
            _id: "studio_2",
            title: "MAPPA",
            createdAt: "2022-01-01",
            updatedAt: "2022-01-01",
        },
        description:
            "Humanity battles Titans to survive in this epic story of survival and betrayal.",
        releaseDate: "2013-04-07",
        episodes: [
            {
                _id: "episode_2",
                title: "To You, 2,000 Years From Now",
                episodeNumber: "1",
                videoUrl: "video_2",
                duration: 24,
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        trailerUrl: "https://example.com/attack-on-titan-trailer.mp4",
        status: "Ongoing",
        createdAt: "2022-01-01",
        updatedAt: "2022-01-01",
    },
    {
        _id: "3",
        title: "Delicious in Dungeon",
        posterUrl: "/fake/4.webp",
        coverUrl: "https://example.com/one-piece-cover.jpg",
        logoUrl: "https://example.com/one-piece-logo.png",
        genres: [
            {
                _id: "genre_5",
                title: "Adventure",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
            {
                _id: "genre_6",
                title: "Comedy",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        studio: {
            _id: "studio_3",
            title: "Toei Animation",
            createdAt: "2022-01-01",
            updatedAt: "2022-01-01",
        },
        description:
            "Monkey D. Luffy sails the Grand Line in search of the One Piece treasure.",
        releaseDate: "1999-10-20",
        episodes: [
            {
                _id: "episode_3",
                title: "I'm Luffy! The Man Who's Gonna Be King of the Pirates!",
                episodeNumber: "1",
                videoUrl: "video_3",
                duration: 22,
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        trailerUrl: "https://example.com/one-piece-trailer.mp4",
        status: "Ongoing",
        createdAt: "2022-01-01",
        updatedAt: "2022-01-01",
    },
    {
        _id: "4",
        title: "Kaiju no. 8",
        posterUrl: "/fake/5.webp",
        coverUrl: "https://example.com/my-hero-academia-cover.jpg",
        logoUrl: "https://example.com/my-hero-academia-logo.png",
        genres: [
            {
                _id: "genre_7",
                title: "Action",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
            {
                _id: "genre_8",
                title: "Superhero",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        studio: {
            _id: "studio_4",
            title: "Bones",
            createdAt: "2022-01-01",
            updatedAt: "2022-01-01",
        },
        description:
            "Follow Izuku Midoriya as he trains to become the world's greatest hero.",
        releaseDate: "2016-04-03",
        episodes: [
            {
                _id: "episode_4",
                title: "Izuku Midoriya: Origin",
                episodeNumber: "1",
                videoUrl: "video_4",
                duration: 23,
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        trailerUrl: "https://example.com/my-hero-academia-trailer.mp4",
        status: "Ongoing",
        createdAt: "2022-01-01",
        updatedAt: "2022-01-01",
    },
    {
        _id: "5",
        title: "Solo Leveling",
        posterUrl: "/fake/6.webp",
        coverUrl: "https://example.com/death-note-cover.jpg",
        logoUrl: "https://example.com/death-note-logo.png",
        genres: [
            {
                _id: "genre_9",
                title: "Mystery",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
            {
                _id: "genre_10",
                title: "Psychological",
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        studio: {
            _id: "studio_5",
            title: "Madhouse",
            createdAt: "2022-01-01",
            updatedAt: "2022-01-01",
        },
        description:
            "Light Yagami finds a notebook that grants him the power to kill.",
        releaseDate: "2006-10-04",
        episodes: [
            {
                _id: "episode_5",
                title: "Rebirth",
                episodeNumber: "1",
                videoUrl: "video_5",
                duration: 24,
                createdAt: "2022-01-01",
                updatedAt: "2022-01-01",
            },
        ],
        trailerUrl: "https://example.com/death-note-trailer.mp4",
        status: "Completed",
        createdAt: "2022-01-01",
        updatedAt: "2022-01-01",
    },
];
